# Generated by Django 4.1.6 on 2023-02-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traits', '0003_alter_trait_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trait',
            name='pets',
        ),
    ]
